{{- if eq .Values.postgresql.enabled false -}}
{{- if not .Values.postgresql.postgresPasswordSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fider.fullname" . }}
  labels:
    app: {{ template "fider.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  postgres-password: {{ .Values.postgresql.postgresPassword | b64enc | quote }}
{{- end -}}
{{- end -}}
