apiVersion: v1
kind: Service
metadata:
  name: {{ include "fider.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "fider.name" . }}
    helm.sh/chart: {{ include "fider.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- toYaml .Values.service.ports | nindent 4 }}
  selector:
    app.kubernetes.io/name: {{ include "fider.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
